import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from 'react';
import { clsx } from 'clsx';
import { useAlert, useUpdateAlertStatus, useSubmitFeedback } from '@/hooks/queries';
import { Badge, Spinner, EmptyState, } from '@/components/shared/ui';
import { ShieldAlert, Sparkles, ThumbsUp, ThumbsDown, Tag, Clock, User, Activity, CheckCircle2, AlertTriangle, FileText, } from 'lucide-react';
// ─────────────────────────────────────────────
// MITRE ATT&CK TACTIC METADATA
// ─────────────────────────────────────────────
const TACTIC_META = {
    TA0001: { name: 'Initial Access', color: 'bg-red-500/15 text-red-400' },
    TA0002: { name: 'Execution', color: 'bg-orange-500/15 text-orange-400' },
    TA0003: { name: 'Persistence', color: 'bg-yellow-500/15 text-yellow-400' },
    TA0004: { name: 'Privilege Escalation', color: 'bg-amber-500/15 text-amber-400' },
    TA0005: { name: 'Defense Evasion', color: 'bg-lime-500/15 text-lime-400' },
    TA0006: { name: 'Credential Access', color: 'bg-teal-500/15 text-teal-400' },
    TA0007: { name: 'Discovery', color: 'bg-cyan-500/15 text-cyan-400' },
    TA0008: { name: 'Lateral Movement', color: 'bg-blue-500/15 text-blue-400' },
    TA0009: { name: 'Collection', color: 'bg-indigo-500/15 text-indigo-400' },
    TA0010: { name: 'Exfiltration', color: 'bg-purple-500/15 text-purple-400' },
    TA0011: { name: 'Command and Control', color: 'bg-fuchsia-500/15 text-fuchsia-400' },
    TA0040: { name: 'Impact', color: 'bg-rose-500/15 text-rose-400' },
};
// ─────────────────────────────────────────────
// TIMELINE STEP
// ─────────────────────────────────────────────
function TimelineStep({ icon: Icon, title, subtitle, timestamp, accent, isLast, }) {
    return (_jsxs("div", { className: "flex gap-3", children: [_jsxs("div", { className: "flex flex-col items-center", children: [_jsx("div", { className: clsx('flex-shrink-0 h-8 w-8 rounded-full flex items-center justify-center', accent), children: _jsx(Icon, { className: "h-4 w-4" }) }), !isLast && _jsx("div", { className: "w-px flex-1 bg-gray-800 mt-1 min-h-4" })] }), _jsxs("div", { className: "pb-4 min-w-0", children: [_jsxs("div", { className: "flex items-baseline gap-2", children: [_jsx("p", { className: "text-sm font-medium text-gray-200", children: title }), _jsx("p", { className: "text-xs text-gray-600 flex-shrink-0", children: timestamp })] }), subtitle && _jsx("p", { className: "text-xs text-gray-500 mt-0.5", children: subtitle })] })] }));
}
// ─────────────────────────────────────────────
// MAIN WORKFLOW PANEL
// ─────────────────────────────────────────────
export function AlertWorkflowPanel({ alertId }) {
    const [activeTab, setActiveTab] = useState('narrative');
    const [showAllEvidence, setShowAllEvid] = useState(false);
    const { data, isLoading, refetch } = useAlert(alertId);
    const { mutate: updateStatus, isPending: updatingStatus } = useUpdateAlertStatus();
    const { mutate: submitFeedback, isPending: submittingFB } = useSubmitFeedback();
    if (isLoading) {
        return (_jsxs("div", { className: "flex flex-col h-full items-center justify-center", children: [_jsx(Spinner, { size: "lg" }), _jsx("p", { className: "mt-4 text-sm text-gray-500", children: "Loading alert\u2026" })] }));
    }
    if (!data?.data) {
        return (_jsx(EmptyState, { icon: ShieldAlert, title: "Alert not found", description: "This alert may have been deleted or you don't have access." }));
    }
    const alert = data.data;
    const severityGradient = {
        critical: 'from-red-900/20 via-transparent',
        high: 'from-orange-900/15 via-transparent',
        medium: 'from-yellow-900/10 via-transparent',
        low: 'from-blue-900/10 via-transparent',
    };
    const severityBorder = {
        critical: 'border-red-500/30',
        high: 'border-orange-500/30',
        medium: 'border-yellow-500/30',
        low: 'border-blue-500/30',
    };
    const tabs = [
        { id: 'narrative', label: 'AI Narrative', icon: Sparkles, count: null },
        { id: 'evidence', label: 'Evidence', icon: Tag, count: alert.evidence?.length ?? 0 },
        { id: 'timeline', label: 'Timeline', icon: Clock, count: null },
    ];
    return (_jsxs("div", { className: "flex flex-col h-full overflow-hidden", children: [_jsxs("div", { className: clsx('flex-shrink-0 p-6 bg-gradient-to-b border-b', severityGradient[alert.severity] ?? 'from-transparent', severityBorder[alert.severity] ?? 'border-gray-800'), children: [_jsxs("div", { className: "flex items-center gap-2 flex-wrap mb-3", children: [_jsx(Badge, { variant: alert.priority, children: alert.priority }), _jsx(Badge, { variant: alert.severity, dot: true, children: alert.severity }), _jsx(Badge, { variant: alert.status, children: alert.status.replace('_', ' ') }), alert.mttdSlaBreached && (_jsxs("span", { className: "inline-flex items-center gap-1.5 px-2 py-0.5 rounded-full\n                             text-xs font-medium bg-red-500/15 text-red-400 ring-1 ring-red-500/30", children: [_jsx(AlertTriangle, { className: "h-3 w-3" }), "SLA Breached"] }))] }), _jsx("h2", { className: "text-xl font-bold text-gray-100 leading-snug mb-2", children: alert.title }), _jsx("p", { className: "text-sm text-gray-400 leading-relaxed line-clamp-3", children: alert.description }), _jsxs("div", { className: "mt-4 grid grid-cols-2 gap-x-6 gap-y-2 text-xs", children: [alert.affectedUserId && (_jsxs("div", { className: "flex items-center gap-2 text-gray-500", children: [_jsx(User, { className: "h-3.5 w-3.5 text-gray-700" }), _jsx("span", { className: "font-mono text-gray-400 truncate", children: alert.affectedUserId })] })), alert.affectedIp && (_jsxs("div", { className: "flex items-center gap-2 text-gray-500", children: [_jsx(Activity, { className: "h-3.5 w-3.5 text-gray-700" }), _jsx("span", { className: "font-mono text-gray-400", children: alert.affectedIp })] })), _jsxs("div", { className: "flex items-center gap-2 text-gray-500", children: [_jsx(Clock, { className: "h-3.5 w-3.5 text-gray-700" }), _jsx("span", { children: new Date(alert.createdAt).toLocaleString() })] }), alert.detectionGapMinutes != null && (_jsxs("div", { className: "flex items-center gap-2 text-gray-500", children: [_jsx(Clock, { className: "h-3.5 w-3.5 text-blue-600" }), _jsxs("span", { children: ["MTTD: ", _jsxs("strong", { className: "text-gray-300", children: [alert.detectionGapMinutes, "m"] })] })] }))] })] }), _jsx("div", { className: "flex-shrink-0 border-b border-gray-800 bg-gray-900/70 px-6 py-3", children: _jsxs("div", { className: "flex items-center gap-2 flex-wrap", children: [_jsx("span", { className: "text-xs text-gray-600 font-medium uppercase tracking-wider mr-1", children: "Actions:" }), [
                            { status: 'investigating', label: 'Investigate', color: 'bg-yellow-500/10 text-yellow-400 border-yellow-500/20' },
                            { status: 'resolved', label: 'Resolve', color: 'bg-green-500/10 text-green-400 border-green-500/20' },
                            { status: 'suppressed', label: 'Suppress', color: 'bg-gray-700 text-gray-400 border-gray-600' },
                            { status: 'false_positive', label: 'False Positive', color: 'bg-gray-700 text-gray-500 border-gray-700' },
                        ].map(({ status, label, color }) => (_jsx("button", { disabled: updatingStatus || alert.status === status, onClick: () => updateStatus({ alertId: alert.id, status }), className: clsx('px-3 py-1.5 rounded-lg text-xs font-medium border transition-all', alert.status === status
                                ? `${color} opacity-100 cursor-default`
                                : 'border-gray-700 text-gray-500 hover:border-gray-600 hover:text-gray-300', updatingStatus && 'opacity-50'), children: alert.status === status ? `✓ ${label}` : label }, status))), _jsxs("div", { className: "ml-auto flex items-center gap-2", children: [_jsxs("button", { disabled: submittingFB, onClick: () => submitFeedback({ alertId: alert.id, verdict: 'true_positive' }), className: "flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg text-xs font-medium\n                         text-green-400 bg-green-500/10 border border-green-500/20 hover:bg-green-500/20\n                         transition-colors", children: [_jsx(ThumbsUp, { className: "h-3.5 w-3.5" }), " TP"] }), _jsxs("button", { disabled: submittingFB, onClick: () => submitFeedback({ alertId: alert.id, verdict: 'false_positive' }), className: "flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg text-xs font-medium\n                         text-red-400 bg-red-500/10 border border-red-500/20 hover:bg-red-500/20\n                         transition-colors", children: [_jsx(ThumbsDown, { className: "h-3.5 w-3.5" }), " FP"] })] })] }) }), _jsx("div", { className: "flex-shrink-0 flex items-center gap-1 border-b border-gray-800 px-6 pt-3", children: tabs.map(tab => (_jsxs("button", { onClick: () => setActiveTab(tab.id), className: clsx('flex items-center gap-1.5 px-3 py-2 text-sm font-medium border-b-2 transition-all', activeTab === tab.id
                        ? 'text-blue-400 border-blue-500'
                        : 'text-gray-500 border-transparent hover:text-gray-300'), children: [_jsx(tab.icon, { className: "h-3.5 w-3.5" }), tab.label, tab.count != null && tab.count > 0 && (_jsx("span", { className: "ml-0.5 text-xs rounded-full bg-gray-800 px-1.5 text-gray-400", children: tab.count }))] }, tab.id))) }), _jsxs("div", { className: "flex-1 overflow-y-auto", children: [activeTab === 'narrative' && (_jsx("div", { className: "p-6 space-y-5", children: alert.llmNarrative ? (_jsxs(_Fragment, { children: [_jsxs("div", { className: "flex items-center gap-2 mb-1", children: [_jsx(Sparkles, { className: "h-4 w-4 text-blue-400" }), _jsx("span", { className: "text-xs font-semibold text-blue-400 uppercase tracking-wider", children: "AI Investigation Summary" }), _jsx("span", { className: "text-xs text-gray-700 ml-auto", children: alert.llmNarrative.modelUsed })] }), _jsxs("div", { className: "rounded-xl bg-gray-800/50 border border-gray-700/50 p-4", children: [_jsx("p", { className: "text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2", children: "What Happened" }), _jsx("p", { className: "text-sm text-gray-200 leading-relaxed", children: alert.llmNarrative.whatHappened })] }), _jsxs("div", { className: "rounded-xl bg-gray-800/50 border border-gray-700/50 p-4", children: [_jsx("p", { className: "text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2", children: "Why It Matters" }), _jsx("p", { className: "text-sm text-gray-200 leading-relaxed", children: alert.llmNarrative.whyItMatters })] }), _jsxs("div", { className: "rounded-xl bg-blue-500/5 border border-blue-500/15 p-4", children: [_jsx("p", { className: "text-xs font-semibold text-blue-400 uppercase tracking-wider mb-3", children: "Recommended Next Steps" }), _jsx("ol", { className: "space-y-2.5", children: alert.llmNarrative.recommendedNextSteps?.map((step, i) => (_jsxs("li", { className: "flex gap-3 text-sm", children: [_jsx("span", { className: "flex-shrink-0 h-5 w-5 rounded-full bg-blue-500/20\n                                         text-blue-400 text-xs flex items-center justify-center\n                                         font-bold mt-0.5", children: i + 1 }), _jsx("span", { className: "text-gray-300 leading-relaxed", children: step })] }, i))) })] }), _jsxs("div", { className: "rounded-xl bg-gray-800/30 border border-gray-800 p-4", children: [_jsx("p", { className: "text-xs font-semibold text-gray-600 uppercase tracking-wider mb-1.5", children: "Confidence Assessment" }), _jsx("p", { className: "text-xs text-gray-500 italic leading-relaxed", children: alert.llmNarrative.confidenceAssessment })] })] })) : (
                        /* No narrative yet — show recommended actions from rule */
                        _jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-2 mb-4", children: [_jsx(FileText, { className: "h-4 w-4 text-gray-500" }), _jsx("span", { className: "text-xs font-semibold text-gray-500 uppercase tracking-wider", children: "Detection Rule Recommendations" })] }), alert.recommendedActions?.length > 0 ? (_jsx("ol", { className: "space-y-3", children: alert.recommendedActions.map((action, i) => (_jsxs("li", { className: "flex gap-3 rounded-xl bg-gray-800/40 p-3.5", children: [_jsx("span", { className: "flex-shrink-0 h-6 w-6 rounded-full bg-gray-700\n                                         text-gray-300 text-xs flex items-center justify-center\n                                         font-bold", children: i + 1 }), _jsx("p", { className: "text-sm text-gray-300 leading-relaxed pt-0.5", children: action })] }, i))) })) : (_jsx("p", { className: "text-sm text-gray-600 text-center py-8", children: "No recommended actions available." })), !alert.llmNarrative && alert.priority !== 'P3' && alert.priority !== 'P4' && (_jsx("p", { className: "mt-4 text-xs text-gray-700 text-center", children: "AI narrative is being generated\u2026" }))] })) })), activeTab === 'evidence' && (_jsx("div", { className: "divide-y divide-gray-800/60", children: (!alert.evidence || alert.evidence.length === 0) ? (_jsx(EmptyState, { icon: Tag, title: "No evidence events", description: "No individual events were captured for this alert." })) : (_jsxs(_Fragment, { children: [(showAllEvidence ? alert.evidence : alert.evidence.slice(0, 15)).map((ev, i) => (_jsx("div", { className: "px-6 py-4", children: _jsxs("div", { className: "flex items-start justify-between gap-4", children: [_jsxs("div", { className: "min-w-0 flex-1", children: [_jsxs("div", { className: "flex items-center gap-2 flex-wrap", children: [_jsxs("code", { className: "text-xs font-mono text-gray-500", children: [ev.eventId?.slice(0, 16), "\u2026"] }), _jsxs("span", { className: "text-xs text-gray-600", children: [ev.sourceType, " \u00B7 ", ev.eventCategory, " \u00B7 ", ev.eventAction] })] }), _jsxs("div", { className: "mt-1.5 flex items-center gap-4 text-xs", children: [ev.actorUserId && (_jsxs("span", { className: "flex items-center gap-1 text-gray-500", children: [_jsx(User, { className: "h-3 w-3 text-gray-700" }), ev.actorUserId.slice(0, 20)] })), ev.actorIp && (_jsx("span", { className: "font-mono text-gray-500", children: ev.actorIp })), ev.actorIpCountry && (_jsx("span", { className: "text-gray-600", children: ev.actorIpCountry }))] }), ev.targetResource && (_jsxs("p", { className: "mt-1 text-xs text-gray-600 truncate", children: ["\u2192 ", ev.targetResource] }))] }), _jsxs("div", { className: "flex-shrink-0 text-right", children: [_jsx("span", { className: clsx('text-xs px-1.5 py-0.5 rounded font-medium', ev.outcome === 'success' ? 'text-green-400 bg-green-500/10'
                                                            : ev.outcome === 'failure' ? 'text-red-400 bg-red-500/10'
                                                                : 'text-gray-400 bg-gray-800'), children: ev.outcome }), _jsx("p", { className: "text-xs text-gray-700 mt-1", children: ev.eventTime && new Date(ev.eventTime).toLocaleTimeString() })] })] }) }, i))), alert.evidence.length > 15 && !showAllEvidence && (_jsx("div", { className: "p-4 text-center", children: _jsxs("button", { onClick: () => setShowAllEvid(true), className: "text-sm text-blue-400 hover:underline", children: ["Show all ", alert.evidence.length, " events"] }) }))] })) })), activeTab === 'timeline' && (_jsx("div", { className: "p-6", children: _jsxs("div", { className: "space-y-0", children: [_jsx(TimelineStep, { icon: ShieldAlert, title: "Alert created", subtitle: `Priority: ${alert.priority} · Severity: ${alert.severity}`, timestamp: new Date(alert.createdAt).toLocaleString(), accent: "bg-red-500/20 text-red-400" }), alert.firstSignalTime && (_jsx(TimelineStep, { icon: Activity, title: "First signal detected", subtitle: `${alert.detectionGapMinutes ?? '?'}m before alert creation`, timestamp: new Date(alert.firstSignalTime).toLocaleString(), accent: "bg-orange-500/20 text-orange-400" })), alert.assignedTo && alert.assignedAt && (_jsx(TimelineStep, { icon: User, title: "Assigned to analyst", subtitle: alert.assignedTo.slice(0, 20), timestamp: new Date(alert.assignedAt).toLocaleString(), accent: "bg-blue-500/20 text-blue-400" })), alert.llmNarrativeGeneratedAt && (_jsx(TimelineStep, { icon: Sparkles, title: "AI narrative generated", subtitle: `Model: ${alert.llmNarrative?.modelUsed}`, timestamp: new Date(alert.llmNarrativeGeneratedAt).toLocaleString(), accent: "bg-purple-500/20 text-purple-400" })), alert.status === 'investigating' && (_jsx(TimelineStep, { icon: Activity, title: "Investigation started", subtitle: "Analyst is actively investigating", timestamp: new Date(alert.updatedAt).toLocaleString(), accent: "bg-yellow-500/20 text-yellow-400" })), alert.resolvedAt && (_jsx(TimelineStep, { icon: CheckCircle2, title: `Alert ${alert.status.replace('_', ' ')}`, subtitle: "", timestamp: new Date(alert.resolvedAt).toLocaleString(), accent: "bg-green-500/20 text-green-400", isLast: true }))] }) }))] })] }));
}
